pipeline:
  name: build
  identifier: build
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gowebdemo
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build docker image
                  identifier: Echo_start_of_build
                  spec:
                    shell: Sh
                    command: |-
                      set -e
                      docker build -t demo-web-server:${HARNESS_BUILD_ID} .
                      docker build -t demo-web-server:latest .
